### ISSUE TITLE
Trying to open the online-help from the context-help does not work

### ISSUE THREAD

**Issue by grthor** [jcryptool/crypto#153]
If you try to open the online help from a link in the context help (screenshot -- marked red) a BasicIndexOutOfBoundsException is thrown. 
<img width="966" alt="issue_screenshot" src="https://user-images.githubusercontent.com/20046726/33906971-def109d4-df83-11e7-8974-f15082c27cf6.PNG">

```!ENTRY org.eclipse.ui 4 0 2017-12-12 21:26:34.637
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.emf.common.util.AbstractEList$BasicIndexOutOfBoundsException: index=1, size=0
	at org.eclipse.emf.common.util.AbstractEList.add(AbstractEList.java:336)
	at org.eclipse.e4.ui.workbench.renderers.swt.ToolBarManagerRenderer.reconcileManagerToModel(ToolBarManagerRenderer.java:957)
	at org.eclipse.ui.internal.e4.compatibility.ActionBars.updateActionBars(ActionBars.java:99)
	at org.eclipse.ui.SubActionBars.updateActionBars(SubActionBars.java:622)
	at org.eclipse.help.ui.internal.views.ReusableHelpPart$HelpPartPage.setVisible(ReusableHelpPart.java:531)
	at org.eclipse.help.ui.internal.views.ReusableHelpPart.flipPages(ReusableHelpPart.java:1069)
	at org.eclipse.help.ui.internal.views.ReusableHelpPart.showPage(ReusableHelpPart.java:1036)
	at org.eclipse.help.ui.internal.views.ReusableHelpPart.openInternalBrowser(ReusableHelpPart.java:1310)
	at org.eclipse.help.ui.internal.views.ReusableHelpPart.showURL(ReusableHelpPart.java:1289)
	at org.eclipse.help.ui.internal.views.ReusableHelpPart.lambda$2(ReusableHelpPart.java:1266)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.help.ui.internal.views.ReusableHelpPart.showURL(ReusableHelpPart.java:1266)
	at org.eclipse.help.ui.internal.views.ContextHelpPart.doOpenLink(ContextHelpPart.java:258)
	at org.eclipse.help.ui.internal.views.ContextHelpPart.access$3(ContextHelpPart.java:252)
	at org.eclipse.help.ui.internal.views.ContextHelpPart$2.linkActivated(ContextHelpPart.java:153)
	at org.eclipse.ui.forms.widgets.FormText.activateLink(FormText.java:1550)
	at org.eclipse.ui.forms.widgets.FormText.handleMouseClick(FormText.java:1359)
	at org.eclipse.ui.forms.widgets.FormText.access$12(FormText.java:1330)
	at org.eclipse.ui.forms.widgets.FormText$2.mouseUp(FormText.java:437)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:221)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.jcryptool.core.Application.start(Application.java:44)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)```

**Comment by grthor** [comment]
There is an entry in Eclipse Bugzilla about this bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=444472. Unfortunately the bug is not solved yet.

**Comment by simlei** [comment]
Looking into this today...

**Comment by simlei** [comment]
Looking into this today. First findings: This seems patchable from what I read:

eclipse forum user Holger Friedrich claims he has made the problem go away in his version by fixing bug [1] and [2], pointing to the patched lines. From what I see, his suggested patch for [1] has been integrated in the meantime as can be seen in [3] - even if the bug itself is not officially marked as resolved. [2] however seems not yet fixed. [4] points to the exact line Mr. Friedrich refers to as of 02/2015; [5] points to the equivalent line as of today; the fix has not been applied here.

I will try to build a custom bundle incorporating a fixed [5] and put it into our target Platform. If that works and we get the change upstream, this is the optimal solution for everyone.


[1] https://bugs.eclipse.org/bugs/show_bug.cgi?id=444472
[2] https://bugs.eclipse.org/bugs/show_bug.cgi?id=459150
[3] [org/eclipse/e4/ui/workbench/renderers/swt/MenuManagerRenderer.java#L1072](https://github.com/eclipse/eclipse.platform.ui/blob/6e81cf13d50ce5b0a34eda38435a0714fd11f4fe/bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/MenuManagerRenderer.java#L1072)
[4] [02/2015 org/eclipse/e4/ui/internal/workbench/ModelServiceImpl.java#L922](https://github.com/eclipse/eclipse.platform.ui/blob/4ced8ee491c0c700fe143db6bf57977c59cc20c2/bundles/org.eclipse.e4.ui.workbench/src/org/eclipse/e4/ui/internal/workbench/ModelServiceImpl.java#L922)
[5] [08/2019: org/eclipse/e4/ui/internal/workbench/ModelServiceImpl.java#L959](https://github.com/eclipse/eclipse.platform.ui/blob/6e81cf13d50ce5b0a34eda38435a0714fd11f4fe/bundles/org.eclipse.e4.ui.workbench/src/org/eclipse/e4/ui/internal/workbench/ModelServiceImpl.java#L959)

**Comment by simlei** [comment]
Still on it...

**Comment by simlei** [comment]
Continuing this in https://github.com/jcryptool/core/issues/153 as this is not fixable in the crypto repository
