### ISSUE TITLE
Public Key Infrastructure: Certificates are not created

### ISSUE THREAD

**Issue by grthor** [jcryptool/crypto#167]
A Certificate Signing Request is only accepted if there is no RSA key pair named "JCT-PKI Root Certificates" in the Key Store. 

To reproduce this error you request a new certificate. This request must be accepted in the certifiaction authority tab. Then close the JCT and start it again. Now request a new certificate. In the registration authority tab check its identity and mark it as valid. Go on to the certification authority tab and accept the certificate signing request. When pressing the accept request button an IndexOutOfBoundsException is thrown.

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at org.jcryptool.visual.jctca.CertificateClasses.CertificateCSRR.getCAKey(CertificateCSRR.java:216)
	at org.jcryptool.visual.jctca.listeners.CAListener.handleCSR(CAListener.java:265)
	at org.jcryptool.visual.jctca.listeners.CAListener.widgetSelected(CAListener.java:103)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.jcryptool.visual.jctca.RegistrarViews.VerifyIdentity.open(VerifyIdentity.java:84)
	at org.jcryptool.visual.jctca.RegistrarViews.VerifyIdentity.widgetSelected(VerifyIdentity.java:159)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.jcryptool.visual.jctca.RegistrarViews.VerifyIdentity.open(VerifyIdentity.java:84)
	at org.jcryptool.visual.jctca.RegistrarViews.VerifyIdentity.widgetSelected(VerifyIdentity.java:159)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.jcryptool.visual.jctca.RegistrarViews.VerifyIdentity.open(VerifyIdentity.java:84)
	at org.jcryptool.visual.jctca.RegistrarViews.VerifyIdentity.widgetSelected(VerifyIdentity.java:159)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.jcryptool.core.Application.start(Application.java:44)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
```

I investigated the problem. CheckCertificatesAndCRL in ```org.jcryptool.visual.jctca.CertificateClasses.CertificateCSRR.java``` checks if there is already a certificate named "JCT-PKI Root Certificates". If a certificate already exists, only the certificate of the CA is loaded, but not the private key of the CA, which is necessary to create the new certificate. This will cause that there is no key in ```ArrayList <AsymmetricCipherKeyPair> caKeys```. When 
```
    /**
     * private ca-key for the index
     * 
     * @param i - the index
     * @return private key
     */
    public AsymmetricCipherKeyPair getCAKey(int i) {
        return caKeys.get(i);
    }
``` 
tries to return an AsymmetricCipherKeyPair the IndexOutOfBoundsException is thrown.

## Feature Request
**In the Plugin outdated X.509 Version 1 certificates are created. It would be better if the up to date Version 3 of the certificates would be created.**

**Comment by simlei** [comment]
Currently this issue is even shadowed by the Java11 migration: (TODO: link it) - On Certificate Request during repro, I get an exception:

```
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBContext
	at org.jcryptool.crypto.keystore.ui.views.nodes.ContactStore.read(ContactStore.java:43)
	at org.jcryptool.crypto.keystore.ui.views.nodes.ContactManager.getContactStore(ContactManager.java:176)
	at org.jcryptool.crypto.keystore.ui.views.nodes.ContactManager.addContact(ContactManager.java:217)
```

**Comment by simlei** [comment]
As this is quite complicated to fix, we push fixing this off until after the v1.0 release.
To fix it, we must move, consistently, from X509v1 to v3.

**Comment by simlei** [comment]
First TODO: remove from the feature for the release

**Comment by simlei** [comment]
Removed this feature
