### ISSUE TITLE
As a general rule: All plugin titles and descriptions should be markable and copyable.

### ISSUE THREAD

**Issue by grthor** [jcryptool/crypto#226]

**Comment by simlei** [comment]
I think this is an ideal candidate for a wiki page where we start to list plug-ins that do not meet this standard ("Non-issue parts").

**Comment by be4** [comment]
Good idea, agreed.

Am 14.10.2019 um 16:57 schrieb Simon Leischnig:
> I think this is an ideal candidate for a wiki page where we start to list plug-ins that do not meet this standard ("Non-issue parts").
>

**Comment by grthor** [comment]
I am currently working on this. I think we can close this after my work is done.

**Comment by grthor** [comment]
**I have developed a composite which allows to mark the plugin title and the plugin description in one go.** 

The composite is easy to use, you create it just like any other composite, add data to the layout and then simply set the title and description with `TitleAndDescriptionComposite#setTitle(String title)` and `TitleAndDescriptionComposite#setDescription(String description)`. The composite takes care of the rest.

Now something about how it works: The composite contains a StyledText that contains the title and the description, that' s why you can select both in one go. The title gets the font `FonteService.getHeaderFont()` (default header font) via a StyleRange.
Now to the biggest problem, what the composite solves: The long vertical scrollbar if it is used in a scrolled composite. The composite checks recursively if it is inside a scrolled composite. If it is, a ResizeListener is added to the ScrolledComposite. Within the listener, the correct size for the content of the scrolled composite is calculated (content = first child of the scrolled composite). Additionally, the StyledText contains a Resize Listener. After the vertical size of the StyledText has changed (e.g. due to line wrap) the Resize Listener of the ScrolledComposite is triggered and the size of the content of the ScrolledComposite is recalculated. Thus the vertical scrollbar is now always correct. The new composite improves other plugins where line breaks were previously forced by "\n" or widthHints.

This is how it looks like:

![image](https://user-images.githubusercontent.com/20046726/77224376-57f89800-6b65-11ea-8a78-98f5966e5203.png)
![image](https://user-images.githubusercontent.com/20046726/77224381-6646b400-6b65-11ea-8fff-03a59b99a161.png)
![image](https://user-images.githubusercontent.com/20046726/77224384-6e065880-6b65-11ea-9f12-ec2768cbd738.png)

**Unfortunately there are now two problems with the composite.** 
1. Sometimes the last word of the description is displayed in a new line that is not shown. I think it is due to the StyleRange, but I am not sure about this. I will further investiate it. 
2. After marking the text and unmarking it there is a blue line staying. I think this is also caused by the Style Range. Further investigating it.
![image](https://user-images.githubusercontent.com/20046726/77224456-0f8daa00-6b66-11ea-8095-94aea8184dcd.png)

Here is a link to the code of the new composite https://github.com/jcryptool/core/blob/develop/org.jcryptool.core.util/src/org/jcryptool/core/util/ui/TitleAndDescriptionComposite.java

**Comment by Leikani** [comment]
Hallo Herr Groos,

das ist großartig und löst ein lange vorhandenes Problem, das immer
wieder sichtbare Unterschiede in verschiedenen Plugins verursachte.

The remaining problem 1 should be solved; problem 2 is not so urgent.

Please document in the wiki that all new authors of plugins use this new
composite.

Thanks a lot, BE


Am 21.03.2020 um 11:22 schrieb Thorben Groos:
> **I have developed a composite which allows to mark the plugin title and the plugin description in one go.** 
>
> The composite is easy to use, you create it just like any other composite, add data to the layout and then simply set the title and description with TitleAndDescriptionComposite#setTitle(String title) and TitleAndDescriptionComposite#setDescription(String description). The composite takes care of the rest.
>
> Now something about how it works: The composite contains a StyledText that contains the title and the description, that' s why you can select both in one go. The title gets the font FonteService.getHeaderFont() (default header font) via a StyleRange.
> Now to the biggest problem, what the composite solves: The long vertical scrollbar if it is used in a scrolled composite. The composite checks recursively if it is inside a scrolled composite. If it is, a ResizeListener is added to the ScrolledComposite. Within the listener, the correct size for the content of the scrolled composite is calculated (content = first child of the scrolled composite). Additionally, the StyledText contains a Resize Listener. After the vertical size of the StyledText has changed (e.g. due to line wrap) the Resize Listener of the ScrolledComposite is triggered and the size of the content of the ScrolledComposite is recalculated. Thus the vertical scrollbar is now always correct. The new composite improves other plugins where line breaks were previously forced by "\n" or widthHints.
>
> This is how it looks like:
>
> ![image](https://user-images.githubusercontent.com/20046726/77224376-57f89800-6b65-11ea-8a78-98f5966e5203.png)
> ![image](https://user-images.githubusercontent.com/20046726/77224381-6646b400-6b65-11ea-8fff-03a59b99a161.png)
> ![image](https://user-images.githubusercontent.com/20046726/77224384-6e065880-6b65-11ea-9f12-ec2768cbd738.png)
>
> **Unfortunately there are now two problems with the composite.** 
> 1. Sometimes the last word of the description is displayed in a new line that is not shown. I think it is due to the StyleRange, but I am not sure about this. I will further investiate it. 
> 2. After marking the text and unmarking it there is a blue line staying. I think this is also caused by the Style Range. Further investigating it.
> ![image](https://user-images.githubusercontent.com/20046726/77224456-0f8daa00-6b66-11ea-8095-94aea8184dcd.png)
>
> Here is a link to the code of the new composite https://github.com/jcryptool/core/blob/develop/org.jcryptool.core.util/src/org/jcryptool/core/util/ui/TitleAndDescriptionComposite.java
>
>
>

**Comment by simlei** [comment]
Awesome, I think these custom controls are the way to go for overall consistency!

**Comment by grthor** [comment]
Thank you both.

You can take a look at the new Composite in the Grille-Analysis and the Ant Colony Optimization Plugin in todays WB.

I will add a note to the wiki.

**Comment by grthor** [comment]
I fixed problem 1: "Sometimes the last word of the description is displayed in a new line that is not shown."

It was caused by a wrong width hint. I checked the available space with
`parent.getClientArea()`
, but missed that the the styledText contained in parent adds 5 px around the widget. Now with 
`parent.getClientArea() -10`
it works correct.

**Comment by grthor** [comment]
I could clearly trace the problem with the blue underline back to the StyleRange. 
If you comment this code out, the error does not occur.

If you comment out the code you will have no more bold headline and no space between title and description.

https://github.com/jcryptool/core/blob/f2ae711ecd511edf1b1b02ad15ec440446f31cc5/org.jcryptool.core.util/src/org/jcryptool/core/util/ui/TitleAndDescriptionComposite.java#L123-L132

**Comment by be4** [comment]
If commenting this out not only has this advantage, but also this
disadvantage, I recommend to not comment out anything.
The blue underline doesn't disturb much and maybe StyleRange gets a fix
in the net release.

Best regards, BE

Am 24.03.2020 um 09:54 schrieb Thorben Groos:
> I could clearly trace the problem with the blue underline back to the StyleRange. 
> If you comment this code out, the error does not occur.
>
> If you comment out the code you will have no more bold headline and no space between title and description.
>
> https://github.com/jcryptool/core/blob/f2ae711ecd511edf1b1b02ad15ec440446f31cc5/org.jcryptool.core.util/src/org/jcryptool/core/util/ui/TitleAndDescriptionComposite.java#L123-L133
>

**Comment by grthor** [comment]
All analysis plugins use the new TitleAndDescriptioComposite.

Now I start to change the visualizations.

**Comment by simlei** [comment]
https://github.com/jcryptool/core/commit/3d45d348dfa4abe7bd89e2b342e0e647b1b1b33c introduces the class `LayoutAdvisor` which can statically hook into SWT layouts and already implements the depth search for `SWT.WRAP`-styled controls that have a `GridData`, and sets their widthHint, if up to then unset.

51e21c60c602a6de3dd77c7947424f4b8cd49261 shows the usage in two plugins where it also directly implements the `TitleAndDescriptionComposite`: RSA and extended RSA visuals.

The diffs are quite concise in explaining the use of it, so I'll leave it to that.

But, I could not see in those plugins any bad change resulting from the use of `TitleAndDescriptionComposite`. To verify, please test out the code and adapt it to your needs. `LayoutAdvisor` already has a few useful debugging output lines, which are commented right now.

**Comment by grthor** [comment]
Works well. But I would have the widthHint calculated not only for controls with SWT.WRAP, but for all controls. Controls without SWT.WRAP also extend horizontally for long texts.
With RSA and extended RSA, this change does not cause problems.

This is the link to my changes: https://github.com/jcryptool/core/commit/fd39964cc04c93c5671b9b63d129a5ebef182027

The only problem I have found is that controls that are not created at the start of a plugin, but later, do not get a widthHint set. But this is rather a special case, except for AntColonyOptimization I haven't seen this anywhere.
I also don't know how to include these controls.

**Comment by simlei** [comment]
> Controls without SWT.WRAP also extend horizontally for long texts.

I think this is intended behavior. After all, what else should they do? Not render above a certain width?
Labels with `SWT.WRAP` and Texts with "SWT.MULTI" are the only controls I can think of that offer the possibility to render the full content without forcing a very large layout width. The width of the wrap is a degree of freedom which is the cause of our `ScrolledComposite` problems, because a scrolled Composite's inner content has infinite horizontal space. Therefore, only with controls listed before that have this degree of freedom, we need the `widthHint`.

> The only problem I have found is that controls that are not created at the start of a plugin, but later, do not get a widthHint set. But this is rather a special case, except for AntColonyOptimization I haven't seen this anywhere.

yes, true. It should be enough to call the LayoutAdvisor method again on the root Composite. I'll think of something better over the weekend. It might be good to already name this "updating" call differently, e.g. `layoutUpdated(rootComposite, updatedChild)`.

**Comment by simlei** [comment]
- [x] `./org.jcryptool.analysis.entropy` does not have title and description composite
- [x] `./org.jcryptool.games.divide` does not have title and description composite
- [x] `./org.jcryptool.games.numbershark` does not have title and description composite
- [x] `./org.jcryptool.games.zudoku` does not have title and description composite
- [x] `./org.jcryptool.visual.aup` does not have title and description composite
- [x] `./org.jcryptool.visual.babystepgiantstep` does not have title and description composite
- [x] `./org.jcryptool.visual.elGamal` does not have title and description composite
- [x] `./org.jcryptool.visual.jctca` does not have title and description composite
- [x] `./org.jcryptool.visual.library` does not have title and description composite
- [x] `./org.jcryptool.visual.merkleHellman` does not have title and description composite https://github.com/jcryptool/crypto/commit/c1fbc1a5c14ef8ad32a0dd8039720ef20682bf28
- [x] `./org.jcryptool.visual.merkletree` does not have title and description composite
- [x] `./org.jcryptool.visual.secretsharing` does not have title and description composite
- [x] `./org.jcryptool.visual.sidechannelattack.dpa` does not have title and description composite
- [x] `./org.jcryptool.visual.sidechannelattack.spa` does not have title and description composite https://github.com/jcryptool/crypto/commit/b745c4162a65dc24c4d06d840e6894dc80b7bfb7
- [x] `./org.jcryptool.visual.sig` does not have title and description composite
- [x] `./org.jcryptool.visual.sigVerification` does not have title and description composite
- [x] `./org.jcryptool.visual.sphincs` does not have title and description composite
- [x] `./org.jcryptool.visual.sphincsplus` does not have title and description composite
- [x] `./org.jcryptool.visual.ssl` does not have title and description composite
- [x] `./org.jcryptool.visual.verifiablesecretsharing` does not have title and description composite
- [x] `./org.jcryptool.visual.wots` does not have title and description composite

**Comment by simlei** [comment]
@grthor I will go through all views with missing title-and-description-composites in the next hours
just FYI for the sake of avoiding conflicts

**Comment by simlei** [comment]
> [x] `./org.jcryptool.analysis.entropy` does not have title and description composite [e4c1104](https://github.com/jcryptool/crypto/commit/e4c110428e4e2d93af5ca1af354e8a819ca0b7fe)

@grthor The linked commit did not pertain to the path in front of it, I deleted it

**Comment by simlei** [comment]
All plugins now have `TitleAndDescriptionComposite`.

However as far as I can tell there is a bug with that custom composite:

@grthor can you take a look please, as I can't seem to find out why. The stack trace does not identify the culprit, but I have isolated that it is in `/org.jcryptool.visual.secretsharing/src/org/jcryptool/visual/secretsharing/views/ShamirsSecretSharingComposite.java`. That is, if nothing really weird is going on... For me, the error happens when opening Shamir's secret sharing view. If remove / comment the title composite in the file, the error disappaers.

However, in the whole file there is no trace of a `FillLayout` as is referenced in the error, *(see below)*. I'm pretty sure this has to do with the automatic listeninc / changes on the SWT tree that you implemented there, and it does things that aren't applicable to this plugin (but no idea why that is).

```
!ENTRY org.eclipse.ui 4 0 2020-04-29 17:23:32.851
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.ClassCastException: class org.eclipse.swt.layout.GridData cannot be cast to class org.eclipse.swt.layout.FillData (org.eclipse.swt.layout.GridData and org.eclipse.swt.layout.FillData are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @6e0e4d38)
	at org.eclipse.swt.layout.FillLayout.flushCache(FillLayout.java:176)
	at org.eclipse.swt.widgets.Composite.layout(Composite.java:1242)
	at org.eclipse.swt.widgets.Control.requestLayout(Control.java:4502)
	at org.jcryptool.core.util.ui.TitleAndDescriptionComposite.lambda$0(TitleAndDescriptionComposite.java:46)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5618)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1405)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1431)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1410)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:1302)
	at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1599)
	at org.eclipse.swt.widgets.Canvas.setBounds(Canvas.java:473)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:1082)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:697)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:201)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1814)
	at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1602)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:1082)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:697)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:201)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1814)
	at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1602)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:1042)
	at org.eclipse.swt.custom.ScrolledCompositeLayout.layout(ScrolledCompositeLayout.java:121)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1814)
	at org.eclipse.swt.widgets.Composite.layout(Composite.java:1113)
	at org.eclipse.swt.widgets.Composite.layout(Composite.java:1065)
	at org.eclipse.swt.custom.ScrolledComposite.setMinSize(ScrolledComposite.java:619)
	at org.eclipse.swt.custom.ScrolledComposite.setMinSize(ScrolledComposite.java:598)
	at org.jcryptool.core.util.ui.TitleAndDescriptionComposite.lambda$1(TitleAndDescriptionComposite.java:103)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5618)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1405)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1431)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1410)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:1302)
	at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1599)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:1082)
	at org.eclipse.swt.layout.FillLayout.layout(FillLayout.java:207)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1814)
	at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1602)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:1082)
	at org.eclipse.swt.layout.FillLayout.layout(FillLayout.java:222)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1814)
	at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1602)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:1082)
	at org.eclipse.swt.layout.FillLayout.layout(FillLayout.java:207)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1814)
	at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1602)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:1042)
	at org.eclipse.swt.custom.CTabFolderLayout.layout(CTabFolderLayout.java:119)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1814)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1820)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1820)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1820)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1820)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1820)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1820)
	at org.eclipse.swt.widgets.Composite.setLayoutDeferred(Composite.java:1661)
	at org.eclipse.swt.widgets.Display.runDeferredLayouts(Display.java:4906)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4393)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:633)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jcryptool.core.Application.start(Application.java:50)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)
```

**Comment by grthor** [comment]
Fixed with https://github.com/jcryptool/crypto/commit/02c7ea4a3183ff3e0f039cae69b125b49492a7ad

The problem was, that in the `createPartControl(Composite parent)` a composite set GridData to `parent`, but `parent` uses FillLayout by default.

There are two ways to avoid this error.
1. Do not set any layout data to `parent` except of FilllData.
2. Set GridLayout as layout type to `parent` explicitly. Then you can use GridData on `parent`.

In this case I fixed it by removing the gridData assignment from the composite. I think this is the better solution for the problem as setting GridLayout to parent, because it has no impact on the GUI at all.

**Comment by simlei** [comment]
Ah. That makes sense. Thanks!
