### ISSUE TITLE
SPHINCS visualization misbehaves

### ISSUE THREAD

**Issue by simlei** [jcryptool/crypto#270]
Plugin path: /org.jcryptool.visual.sphincsplus

A video tells it best:

![Peek 2019-11-19 17-45](https://user-images.githubusercontent.com/982379/69167588-7ede8900-0af5-11ea-9743-f883af18698f.gif)

During the capture of the video, I get a ton of exceptions thrown because of disposed controls, which usually is a very **bad** sign for visualization implementation when being thrown periodically -- there is something going on in the background.
```txt
org.eclipse.swt.SWTException: Graphic is disposed
    at org.eclipse.swt.SWT.error(SWT.java:4711)
    at org.eclipse.swt.SWT.error(SWT.java:4626)
    at org.eclipse.swt.SWT.error(SWT.java:4597)
    at org.eclipse.swt.graphics.Color.getRed(Color.java:303)
    at org.eclipse.swt.graphics.Color.equals(Color.java:233)
<snip>
```
https://pastebin.com/GMU0CjMp

I realized there is a background process that does not pay attention to resource lifecycle before -- this issue seems at least distantly related: https://github.com/jcryptool/crypto/issues/258

Following https://github.com/eclipse/gef/wiki/Zest-Examples and https://bugs.eclipse.org/bugs/show_bug.cgi?id=469126, I already tried to set SWT_GTK3 to 0 as follows:

But the video is recorded using that setting. I seemed to notice a difference after the change so I'm confident the environment variable was picked up.

![image](https://user-images.githubusercontent.com/982379/69167458-4ccd2700-0af5-11ea-97bc-4a8baa0b6188.png)

Platform: Linux/GTK

**Comment by simlei** [comment]
Due to incompatibility of ZEST feature (graph embedded in graph) with GTK, the two rightmost tabs have been disabled under Linux.
