### ISSUE TITLE
Improvement ideas and bugs: McEliece/Rainbow (ErrorCorrectingCodes/MultivatiateCrypto)

### ISSUE THREAD

**Issue by simlei** [jcryptool/crypto#328]
This concerns the plugins:
- McEliece (`crypto/org.jcryptool.visual.errorcorrectingcodes`)
- Rainbow (`crypto/org.jcryptool.visual.rainbow`)

### Textual issues

- Typos/Grammar McEliece (https://github.com/jcryptool/crypto/commit/8be574b0c69e5cbf5a6407f429ca7621443251e8)
  - [x] [Tab1/EN](https://user-images.githubusercontent.com/982379/89264508-54a50b00-d633-11ea-871a-09f3937ddf4c.png) 
  - [x] [Tab1/DE](https://user-images.githubusercontent.com/982379/89264843-e6147d00-d633-11ea-932f-0b44e50cbed1.png) 
  - [x] [Tab2/EN](https://user-images.githubusercontent.com/982379/89264590-7a321480-d633-11ea-8085-6c923fb5e157.png) 
  - [x] [Tab2/DE](https://user-images.githubusercontent.com/982379/89264996-2116b080-d634-11ea-9912-2827ffe133e2.png) 
  - [x] [Tab3/EN](https://user-images.githubusercontent.com/982379/89264685-a057b480-d633-11ea-9257-0a8462396bb3.png) 
  - [x] [Tab3/DE](https://user-images.githubusercontent.com/982379/89265098-45728d00-d634-11ea-86f3-bf47abe15070.png)

- Typos/Grammar Rainbow (https://github.com/jcryptool/crypto/commit/07121e05d1ee1a0d041260e9108eb128d977456f)
  - [x] [EN](https://user-images.githubusercontent.com/982379/89265479-d6496880-d634-11ea-9dca-e9b5cd602c27.png) 
  - [x] [DE](https://user-images.githubusercontent.com/982379/89265403-b44fe600-d634-11ea-8456-89f04baa02ec.png)

### Help system

- [x] DE/McEliece: question mark button does not open help; help is however present ("TOC/Visual/Fehlerkorrektur Codes") **but empty** (needs translation @ B.E.) (https://github.com/jcryptool/crypto/commit/0a4dcfbc3a93cdbdcdd31f7008c1fc867fa952a9)
- [x] DE/Rainbow : question mark button does not open help; help is not present in the source (https://github.com/jcryptool/crypto/commit/5993f170f37df4a851322534a8cb689734c3edaf)
- [x] EN/McEliece: question mark button does not open help; help is however present ("TOC/Visual/McEliece cryptographic system") (https://github.com/jcryptool/crypto/commit/5993f170f37df4a851322534a8cb689734c3edaf)
- [x] EN/Rainbow : question mark button does not open help; help is however present ("TOC/Visual/Multivariate Cryptography") (https://github.com/jcryptool/crypto/commit/0a4dcfbc3a93cdbdcdd31f7008c1fc867fa952a9)

### Translation

- [x] fix missing translations in the GUI (https://github.com/jcryptool/crypto/commit/8be574b0c69e5cbf5a6407f429ca7621443251e8, https://github.com/jcryptool/crypto/commit/07121e05d1ee1a0d041260e9108eb128d977456f)
- [x] translate online help for McEliece to German ( thanks to https://github.com/jcryptool/crypto/pull/338 )
- [x] translate online help for Rainbow to German ( thanks to https://github.com/jcryptool/crypto/pull/339 )

### Layout

- [ ] Rainbow/Multivar.Krypto -- Layout: Die Formeln unter "Coefficient distribution" sind breiter als der Bereich, ab dem der horizontale Scrollbar angezeigt wird.
- [ ] Rainbow/Multivar.Krypto -- Layout: Auch wenn ich n=7 setze, wird der Platz bis zur Gruppierung "Algorithm details" nicht gnaz beansprucht. Wenn das so ist, dann bitte Gruppierung "Algorithm details" nach oben schieben.
- [x] McEliece: Alice and Bob's private key areas in "Algorithmus" (second tab of McEliece) are way big.
  - [x] McEliece: Third tab: better layout (space waste), less intrusive colors

![image](https://user-images.githubusercontent.com/982379/139870446-317237df-341f-4669-bb89-0154f8a3cd2d.png)

- [ ] Zuviel leerer Platz unter "Coefficient distribution". Dafür wurde unter "Algorithm details" zuerst ein vertikaler Scrollbar nötig.
  - [ ] Die Leerzeile vor "----Public Key----" in "Coefficient distribution" rausnehmen.
- [ ] Die senkrechte Trennlinie verschiebbar machen. Ich würde es so einstellen, dass die linke Seite etwas weniger Platz hat und dafür die rechte mehr. Dann würde man auch alle Koeffizienten (wie O_23) sehen. Wenn unter "Coefficient distribution" nicht alles angezeigt werden kann, sollte es einen horizontaen Scrollbar haben.

**Comment by simlei** [comment]
- [x] @simlei Apply Title-And-Description generic composites to all views and tabs

**Comment by simlei** [comment]
### Bugs: 

1)

McEliece Cryptosystem: the "Decrypt" button yields an error with default inputs and "Generate keys" > "Encrypt" > "Decrypt"
![image](https://user-images.githubusercontent.com/982379/140380789-9df34fff-94ea-4d0d-ae4f-309bee3c1797.png)

```
java.lang.ArithmeticException: length mismatch
	at org.bouncycastle.pqc.math.linearalgebra.GF2Vector.<init>(GF2Vector.java:122)
	at org.bouncycastle.pqc.math.linearalgebra.GF2Vector.OS2VP(GF2Vector.java:182)
	at org.bouncycastle.pqc.crypto.mceliece.McElieceCipher.messageDecrypt(Unknown Source)
	at org.jcryptool.visual.errorcorrectingcodes.algorithm.McElieceCrypto.decrypt(McElieceCrypto.java:166)
	at org.jcryptool.visual.errorcorrectingcodes.ui.views.McElieceView.performDecryption(McElieceView.java:268)
	at org.jcryptool.visual.errorcorrectingcodes.ui.views.McElieceView.lambda$4(McElieceView.java:197)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
```

**Comment by simlei** [comment]
### Functionality improvements

- [ ] Rainbow: Could there be a log file for LES, ideally to open in an editor, so that the parameters and ideally, interim steps can be looked into?
- [ ] Rainbow: provide way to manipulate the parameters other than just the ordinality of the layers — there is little room for playing around with the algorithm
