### ISSUE TITLE
Crash in Transposition analysis (org.jcryptool.analysis.transpositionanalysis)

### ISSUE THREAD

**Issue by tassadarius** [jcryptool/crypto#333]
# Input can produce crash

(Take reproduce from GIF)
Crash seems to happen independently of input text length

![loading_crash](https://user-images.githubusercontent.com/22643766/95207704-6ef09600-07e8-11eb-9afc-fd3169c05110.gif)

Following exception occurs:

```
!ENTRY org.eclipse.help.base 4 4 2020-10-06 15:24:52.343
!MESSAGE Help documentation could not be indexed completely.
!SUBENTRY 1 org.eclipse.help.base 4 4 2020-10-06 15:24:52.343
!MESSAGE Exception occurred while adding document /org.jcryptool.core/overview/overview.xhtml to index.
!STACK 0
java.io.IOException: Stream Closed
	at java.base/java.io.FileInputStream.read0(Native Method)
	at java.base/java.io.FileInputStream.read(FileInputStream.java:231)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager$RewindableInputStream.readAndBuffer(XMLEntityManager.java:3026)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:704)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:150)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:860)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324)
	at java.xml/javax.xml.parsers.SAXParser.parse(SAXParser.java:197)
	at org.eclipse.help.search.SearchParticipantXML.addDocument(SearchParticipantXML.java:294)
	at org.eclipse.help.internal.search.HTMLSearchParticipant.addDocument(HTMLSearchParticipant.java:57)
	at org.eclipse.help.internal.search.SearchIndex.addDocument(SearchIndex.java:1138)
	at org.eclipse.help.internal.search.SearchIndex.addSearchableDocument(SearchIndex.java:1145)
	at org.eclipse.ui.internal.intro.impl.model.IntroSearchParticipant.addPage(IntroSearchParticipant.java:177)
	at org.eclipse.ui.internal.intro.impl.model.IntroSearchParticipant.addDocument(IntroSearchParticipant.java:147)
	at org.eclipse.help.internal.search.SearchIndex.addDocument(SearchIndex.java:255)
	at org.eclipse.help.internal.search.IndexingOperation.addDocuments(IndexingOperation.java:248)
	at org.eclipse.help.internal.search.IndexingOperation.addNewDocuments(IndexingOperation.java:159)
	at org.eclipse.help.internal.search.IndexingOperation.execute(IndexingOperation.java:108)
	at org.eclipse.help.internal.search.LocalSearchManager.updateIndex(LocalSearchManager.java:629)
	at org.eclipse.help.internal.search.LocalSearchManager.ensureIndexUpdated(LocalSearchManager.java:603)
	at org.eclipse.help.internal.search.federated.IndexerJob.run(IndexerJob.java:35)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by simlei** [comment]
Fixed
