### ISSUE TITLE
Frequency Analysis: NullPointerException when opening view

### ISSUE THREAD

**Issue by dschadow** [jcryptool/crypto#95]
Starting the Frequency Analysis view results into an exception and shows only a minimized diagram:

java.lang.NullPointerException
	at org.jcryptool.analysis.freqanalysis.ui.SimpleAnalysisUI.hideObject(SimpleAnalysisUI.java:283)
	at org.jcryptool.analysis.freqanalysis.ui.SimpleAnalysisUI.<init>(SimpleAnalysisUI.java:58)
	at org.jcryptool.analysis.freqanalysis.ui.FreqAnalysisUI.initGUI(FreqAnalysisUI.java:95)
	at org.jcryptool.analysis.freqanalysis.ui.FreqAnalysisUI.<init>(FreqAnalysisUI.java:39)
	at org.jcryptool.analysis.freqanalysis.views.FreqAnalysisView.createPartControl(FreqAnalysisView.java:42)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:140)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityView.createPartControl(CompatibilityView.java:155)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:321)

**Comment by hfriedr** [comment]
It is my impression that this NullPointerException happens when one leaves the Frequency Analysis open when closing down JCrypTool, then restarts JCrypTool.  Simply opening the view from the main menu does not cause an exception.

**Comment by hfriedr** [comment]
Not sure the weird behaviour that may ensue when one leaves the Frequency Analysis open while closing down JCrypTool, then restarts JCrypTool, is entirely gone, but the NullPointerException has certainly been fixed.
